### ISSUE TITLE
crash: crystal peak room with the bunch of lazer crawlers on the way to crystal guardian

### ISSUE THREAD

**Issue by Kerr1291** [Kerr1291/EnemyRandomizer#16]
additional note: crash also happened in crusher room on the east side of crystal peaks

I think the "Crystallised Lazer Bug" was removed from being either a wall or ground type, causing an infinite loop in the type matching...

**Comment by 5FiftySix6** [comment]
*laser crawlers in general

**Comment by 5FiftySix6** [comment]
[ModLog.txt](https://github.com/Kerr1291/EnemyRandomizer/files/1760329/ModLog.txt)
[output_log.txt](https://github.com/Kerr1291/EnemyRandomizer/files/1760332/output_log.txt)
