### ISSUE TITLE
Crash: Room that leads to broken vessel and down to mawleks

### ISSUE THREAD

**Issue by 5FiftySix6** [Kerr1291/EnemyRandomizer#22]
[ModLog.txt](https://github.com/Kerr1291/EnemyRandomizer/files/1760360/ModLog.txt)
[output_log.txt](https://github.com/Kerr1291/EnemyRandomizer/files/1760361/output_log.txt)

**Comment by Kerr1291** [comment]
Note to self: Add "Parasite Balloon" enemy to the type lists..... (cause of crash)
