### ISSUE TITLE
lifeblood bug screenshots

### ISSUE THREAD

**Issue by Kerr1291** [Kerr1291/EnemyRandomizer#31]

**Comment by TheRealMechazawa** [comment]
Weird wall crawler placements, most of them stuck, in one instance one is inside the geometry moving around.


![screenshot 2018-04-28 09 50 42](https://user-images.githubusercontent.com/38813603/39397938-a24fa3aa-4acc-11e8-8ffb-1ae819f534ec.png)
![screenshot 2018-04-28 09 51 07](https://user-images.githubusercontent.com/38813603/39397940-a8b5f08c-4acc-11e8-98a6-92941a4000b4.png)
![screenshot 2018-04-28 09 51 20](https://user-images.githubusercontent.com/38813603/39397942-aac35964-4acc-11e8-903d-cb2604799150.png)
![screenshot 2018-04-28 10 00 22](https://user-images.githubusercontent.com/38813603/39397944-b056bb32-4acc-11e8-8ba3-99a9aa588f4d.png)
![screenshot 2018-04-28 10 01 26](https://user-images.githubusercontent.com/38813603/39397946-b2180f48-4acc-11e8-9ff4-e33825c5f617.png)

**Comment by TheRealMechazawa** [comment]
Green rectangles occasionally pop up.

![screenshot 2018-04-28 10 05 15](https://user-images.githubusercontent.com/38813603/39397957-e27500ce-4acc-11e8-8666-7f538e70f4cd.png)
![screenshot 2018-04-28 09 56 20](https://user-images.githubusercontent.com/38813603/39397961-e743ac04-4acc-11e8-9afd-e6af4e6647c5.png)

**Comment by TheRealMechazawa** [comment]
Instances of smushed monsters. They are numerous.

![screenshot 2018-04-28 10 08 55](https://user-images.githubusercontent.com/38813603/39397973-11d3dfd4-4acd-11e8-9bfa-36bbc886cac7.png)
![screenshot 2018-04-28 10 08 12](https://user-images.githubusercontent.com/38813603/39397976-134c93f6-4acd-11e8-8ba0-f3b52c8af208.png)
![screenshot 2018-04-28 10 07 23](https://user-images.githubusercontent.com/38813603/39397978-15032e62-4acd-11e8-85b0-849a3820dd0a.png)
![screenshot 2018-04-28 10 05 30](https://user-images.githubusercontent.com/38813603/39397985-18086c76-4acd-11e8-9e67-da2aeb27e090.png)
![screenshot 2018-04-28 09 58 33](https://user-images.githubusercontent.com/38813603/39397987-1b4ff7aa-4acd-11e8-9cb7-a9c6b5d5b10a.png)
![screenshot 2018-04-28 09 58 18](https://user-images.githubusercontent.com/38813603/39397988-1c41ce36-4acd-11e8-829e-48f9b0ae8504.png)
![screenshot 2018-04-28 09 53 38](https://user-images.githubusercontent.com/38813603/39397989-1fc36d62-4acd-11e8-9de4-c2a3247224a7.png)
